# =============================== 核心配置 ================================

# --------------- spring ---------------
server:
  port: 8081

spring:
  profiles:
    active: dev

  # ================================= 连接配置 ==================================
  # ---------------- redis ----------------
  # ----------------- mysql ------------------
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
    filters: stat,wall,log4j
  data:
    redis:
      password:
      database: 0
      host: localhost
      port: 6379
      timeout: 1000
